### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [lukasbystricky/lewis-mumford_the-story-of-utopias#1]
# CSS

- [x] Toolset needs to be updated, and core.css and se.css need to be updated to latest version.

# Hyphenation and Spelling

- [x] Run modernize-spelling and accept changes.
- [x] We should resolve the mismatched hyphenation of `overworld` and `over-world` in favor of `overworld`.
- [x] We should change the instances of `Emile` to `Émile`.
- [x] 4d20172a6978ba69d62ca49fa89b241f5d7a1602: I don’t really understand the reasoning behind this change. Who/what is AE and what is that if not an acryonym?
- [x] I think `the <i epub:type="se:name.publication.book">Time Machine</i>` should be `<i epub:type="se:name.publication.book">The Time Machine</i>`
- [x] Similarly `the <i epub:type="se:name.publication.book">Fairy Queen</i>` should be `<i epub:type="se:name.publication.book">The Fairy Queen</i>`
- [x] In chapter 7, you have an ordered list with redunant in-line numbers.
- [x] I think most of your uses of `–` (U+2013, en-dash) should actually be em-dashes. We should do an interactive replace of en-dashes with em-dashes and run typogrify.

# Semantics

- [x] bibliography: `Vorläufer <i epub:type="se:name.publication.book" xml:lang="de">des Modernen Sozialismus</i>` should be `<i epub:type="se:name.publication.book" xml:lang="de">Vorläufer des Modernen Sozialismus</i>`
- [x] Is `<i epub:type="se:name.publication.book">Kingdom of <span xml:lang="grc-Latn">Eutopia</span></i>` actually a book?
- [x] `<i epub:type="se:name.publication.book">Description of Spensonia. Constitution of Spensonia</i>`: I think these are two separate books

# Images

- [x] Run build-images and accept changes.

# Meta

- [x] 54025a0b16f782ac6c803d86205543917ebd9515: I think you accidentally included an erroneous paragraph move in this commit (you eventually reverted it in 7ac8e4e23de7820a39cf7c8c8fefbdbaad6722df but since it’s in an editorial commit we might as well rebase it out entirely).

# Metadata

- [x] Is there anything that indicates that John Bruno Hare specifically transcribed the text? He seems to have been the maintainer at one point but it seems anyone could have done the transcription. It might make more sense to cite the website as a whole.
- [x] Short description should be a complete sentence.

**Comment by lukasbystricky** [comment]
Mostly taken care of. A few points:

- I left "Reflexions on Violence" as is, since that's the name of a book
- AE is a pseudonym for [George Williams Russell](https://en.wikipedia.org/wiki/George_William_Russell). Maybe that could be semanticated somehow? I don't think it's really an abbreviation though.
- On the title page [here](https://sacred-texts.com/utopia/sou/sou00.htm) it says that John Hare proofed and formatted the book.

**Comment by weijia-cheng** [comment]
1. My understanding is that it is called _Réflexions sur la violence_ in French, but in English it is pretty consistently called _Reflections on Violence_. In any case, there is an inconsistency within the original text since it is spelled with a `ct` in [chapter 10](https://archive.org/details/storyofutopiasid00mumf/page/194/mode/2up?q=%22Reflections+on+Violence%22). I think that's a strong indicator that we should modernize it, to make it consistent if nothing else.
2. Should we use the ligature `Æ` instead to make it clearer that it is not an abbreviation? It seems that this is used about as much as `AE`.

**Comment by lukasbystricky** [comment]
Ok, I agree with both those suggestions. I've pushed everything, it should be ready for another look.
